### PR TITLE
Fixing issue #47: Fixing the permission issue for already configured …

### PR DESCRIPTION
**Pull request by Gnyblast**
…output devices on setting value

### CODE REVIEW

**Comment by Gnyblast** [comment]
> You are adding the overhead of reading the line info whenever a line is set, so no. And the kernel will reject that anyway - the line has to be explicitly requested as an output for the set to succeed. Have you tested this?

Yes I tested it and it works.

**Comment by warthog618** [comment]
Ok, now I'm lost.  If you have reconfigured the line to an output then what is the point of your change?  Reconfiguring the line like that is literally no different from requesting it as an output from the start - unless want to read the existing value before the reconfigure.  But then you just set it to 0, so that doesn't seem to be the case.

Btw, the AsActiveHigh is generally not needed - that is the default.  Unless you explicitly requested AsActiveLow earlier.

And I meant, have you tried your change without reconfiguring the line?  That will bypass the permission check in the library (you may as well've just removed it), only to have the same check in the kernel fail.

**Comment by Gnyblast** [comment]
> And I meant, have you tried your change without reconfiguring the line? That will bypass the permission check in the library (you may as well've just removed it), only to have the same check in the kernel fail.

Alright I see it now. No I didn't because as init my application does sanity checks and sets at start and set output pins as output and asHighActive to prevent any previous configs left over there. Same goes for inputs too. Ok I now see you point. You say that, if you don't reconfigure it, then the `l.info()` won't return anything about `Direction`?

**Comment by warthog618** [comment]
The idea is that if you are going to continue to use the lines then you hold the request.  The kernel then guarantees that you are the only one that can access them.  You shouldn't assume the GPIOs will store state between requests.  It happens to work on the Pi, but it is up to the device driver.  And once you release the line other processes can change it as well.

The line info is lazy loaded to avoid pointless reads.  If you never ask for it then it is never loaded.

>  Ok I now see you point. You say that, if you don't reconfigure it, then the `l.info()` won't return anything about `Direction`?

No, if you request an output line as-is, the info will say output, which is the way the driver is currently configured, but the kernel will reject the set unless you explicitly request the line as output, not as-is.  So you either need to request the line as output from the start, or if you want to read the existing value then request it as-is then reconfigure it to output.

**Comment by Gnyblast** [comment]
Alright, it's much clear now. I was thinking in a way that, if GPIO-X is being used with my application, then I'd assume that nothing else would try to use/change it. Then it would always be safe, since I was setting it up as output on startup. But no, as you said something else would also interact with it and might cause panic which makes sense for your library ofc, but in the way that my app works, this would still create big troubles :) Thanks for the explanation.

**Pull request closed without merging**
